name: Run Data Updates

on:

  # Allow manual trigger
  workflow_dispatch:
  
  schedule:
    # Schedule to run daily at 2 AM (UTC timezone)
    - cron: "0 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    # Step 3: Install required R packages
    - name: Install R packages
      run: |
        Rscript -e "install.packages('DBI', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('RMySQL', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('dplyr', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('tidyr', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('readr', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('purr', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('stringr', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('lubridate', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('zoo', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('glue', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('jsonlite', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('Rtools', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('curl', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('openssl', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('stringi', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('xml2', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('rvest', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('reshape2', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('data.table', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('xgboost', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('fastDummies', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('Matrix', repos='http://cran.rstudio.com/')"
        Rscript -e "install.packages('glmnet', repos='http://cran.rstudio.com/')"
        
    # Step 4: Run the R script
    - name: Run R script
      run: Rscript _data_updates.R
