name: Run Data Updates

on:

  # Allow manual trigger
  workflow_dispatch:
  
  schedule:
    # Schedule to run daily at 2 AM (UTC timezone)
    - cron: "0 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Step 3: Install required R packages
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
          packages: |
            any::tidyverse 
            any::DBI
            any::RMySQL
            any::rvest
            any::reshape2
            any::data.table
            any::xgboost
            any::fastDummies
            any::Matrix
            any::glmnet
        
    # Step 4: Run the R script
    - name: Run R script
      run: Rscript _data_updates.R
