name: Run Data Updates

on:
  # Allow manual trigger
  workflow_dispatch:

  # Scheduled trigger (e.g., daily at 3 AM EST / 8 AM UTC)
  schedule:
    - cron: "0 8 * * *"

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::DBI
            any::RMySQL
            any::tidyverse
            any::zoo
            any::glue
            any::jsonlite
            any::rvest
            any::reshape2
            any::data.table
            any::xgboost
            any::fastDummies
            any::Matrix
            any::glmnet

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("_data_updates.R")'
